# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- manual

variables:

  - name: ServiceConnection
    value: 'Azure subscription 1(85f9051c-3d5f-4da3-bc26-5660c9b51169)'

  - name: ResourceGroupName
    value: 'terraformbackend'

  - name: StorageAccountName
    value: 'terraform14586'

  - name: ContainerName
    value: 'tfstate'

  - name: Key
    value: 'dev.terraform.tfstate'

  - name: SubscriptionID
    value: '85f9051c-3d5f-4da3-bc26-5660c9b51169'

stages:
  - stage: Plan
    jobs:
      - job: Plan
        pool:
         vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure subscription 1(85f9051c-3d5f-4da3-bc26-5660c9b51169)'
              backendAzureRmOverrideSubscriptionID: '85f9051c-3d5f-4da3-bc26-5660c9b51169'
              backendAzureRmResourceGroupName: 'terraformbackend'
              backendAzureRmStorageAccountName: 'terraform14586'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev.terraform.tfstate'

          - task: TerraformTask@5
            displayName: Terraform Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Azure subscription 1(85f9051c-3d5f-4da3-bc26-5660c9b51169)'
              environmentAzureRmOverrideSubscriptionID: '85f9051c-3d5f-4da3-bc26-5660c9b51169'

  - stage: Destroy
    jobs:
      - job: Destroy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure subscription 1(85f9051c-3d5f-4da3-bc26-5660c9b51169)'
              backendAzureRmOverrideSubscriptionID: '85f9051c-3d5f-4da3-bc26-5660c9b51169'
              backendAzureRmResourceGroupName: 'terraformbackend'
              backendAzureRmStorageAccountName: 'terraform14586'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev.terraform.tfstate'

          - task: TerraformTask@5
            displayName: Terraform Destroy
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              commandOptions: '--auto-approve'
              environmentServiceNameAzureRM: 'Azure subscription 1(85f9051c-3d5f-4da3-bc26-5660c9b51169)'
              environmentAzureRmOverrideSubscriptionID: '85f9051c-3d5f-4da3-bc26-5660c9b51169'

